Filtering clients and hosts on timeline
ActivityWatch/aw-webui pull request #502
Opened 2023-11-17 22:31 UTC by skaparis

This option enable user to filter  events from different devices or event types on timeline.

2023-11-17 22:44 UTC, ErikBjare requested changes
Neat, just some minor things

2023-11-17 22:44 UTC, ErikBjare commented on src/views/Timeline.vue
> +      filter_client: '*',
Use `null` to indicate no filter instead

2023-11-17 22:44 UTC, ErikBjare commented on src/views/Timeline.vue
> +              option(value='*') *
Re my other comment: You might have to write `:value='null'` here, to read it as a value instead of the `"null"` string.

2023-11-17 22:44 UTC, ErikBjare commented on src/views/Timeline.vue
> +      console.log(this.all_buckets);
And remove the debug logging :)

2023-11-18 11:25 UTC, skaparis commented
Good points, done.

2023-11-19 09:12 UTC, ErikBjare approved these changes

2023-11-19 09:13 UTC, merged

2023-11-19 09:13 UTC, ErikBjare commented
Merged  :tada:

Thanks for your contribution! :heart:

2023-11-19 21:47 UTC, ErikBjare commented
Made some improvements in https://github.com/ActivityWatch/aw-webui/commit/609a7cc8e47bc087307b4c5e6f4eb914f699c099